import { NextResponse } from 'next/server'
export const dynamic = 'force-static'

const comparisons = [
  { category: 'Authentication', tutorLms: 'JWT + OAuth (Google, Facebook, X) + 2FA + reCAPTCHA', lastsaas: 'JWT HS256 + OAuth (GitHub, Google, Microsoft) + MFA + WebAuthn', status: 'equivalent', tutorSource: 'tutor/classes/Frontend.php, tutor-pro/addons/auth/', lastsaasSource: 'lastsaas/backend/internal/auth/, middleware/auth.go', confidence: 'confirmed' },
  { category: 'RBAC', tutorLms: 'admin, instructor, student (WP roles)', lastsaas: 'owner, admin, user (+ planned: instructor, student)', status: 'partially-implemented', tutorSource: 'tutor/classes/User.php', lastsaasSource: 'lastsaas/backend/internal/middleware/rbac.go', confidence: 'confirmed' },
  { category: 'Multi-tenancy', tutorLms: 'WordPress multisite (not true multi-tenant)', lastsaas: 'True multi-tenant with tenant_id on every collection', status: 'different-implementation', tutorSource: 'N/A (WP plugin)', lastsaasSource: 'lastsaas/backend/internal/middleware/tenant.go', confidence: 'confirmed' },
  { category: 'Course Management', tutorLms: 'CourseModel.php (WP custom post type)', lastsaas: 'N/A — new course collection needed', status: 'missing-in-lastsaas', tutorSource: 'tutor/models/CourseModel.php', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'Lesson Management', tutorLms: 'LessonModel.php (WP custom post type)', lastsaas: 'N/A — new lesson collection needed', status: 'missing-in-lastsaas', tutorSource: 'tutor/models/LessonModel.php', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'Quiz System', tutorLms: 'QuizModel.php — 13 question types, attempts, grading', lastsaas: 'N/A — new quiz collections needed', status: 'missing-in-lastsaas', tutorSource: 'tutor/models/QuizModel.php', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'Enrollment', tutorLms: 'EnrollmentModel.php — tutor_enrolled post type', lastsaas: 'N/A — new enrollment collection needed', status: 'missing-in-lastsaas', tutorSource: 'tutor/models/EnrollmentModel.php', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'Ecommerce', tutorLms: 'OrderModel.php, CartModel.php, CouponModel.php — native ecommerce', lastsaas: 'Stripe integration (stripe.go) — no cart/order/coupon yet', status: 'partially-implemented', tutorSource: 'tutor/models/OrderModel.php, CartModel.php, CouponModel.php', lastsaasSource: 'lastsaas/backend/internal/stripe/stripe.go', confidence: 'confirmed' },
  { category: 'Payments', tutorLms: '11 gateways (Stripe, PayPal, Razorpay, Mollie, etc.)', lastsaas: 'Stripe only (CreateCheckoutSession)', status: 'partially-implemented', tutorSource: 'tutor-pro/addons/ (payment gateways)', lastsaasSource: 'lastsaas/backend/internal/stripe/stripe.go', confidence: 'confirmed' },
  { category: 'Subscriptions', tutorLms: 'SubscriptionModel.php — recurring plans', lastsaas: 'Stripe recurring via plans collection + stripe_mappings', status: 'equivalent', tutorSource: 'tutor-pro/addons/subscription/', lastsaasSource: 'lastsaas/backend/internal/stripe/stripe.go, models/plan.go', confidence: 'confirmed' },
  { category: 'Events', tutorLms: '480 do_action() hooks (WordPress action hooks)', lastsaas: '22 typed events in events/emitter.go', status: 'different-implementation', tutorSource: 'tutor/classes/ (do_action calls)', lastsaasSource: 'lastsaas/backend/internal/events/emitter.go', confidence: 'confirmed' },
  { category: 'Middleware', tutorLms: 'N/A (WordPress plugin architecture)', lastsaas: '10 middleware: auth, rbac, tenant, ratelimit, security, recovery, etc.', status: 'lastsaas-only', tutorSource: 'N/A', lastsaasSource: 'lastsaas/backend/internal/middleware/', confidence: 'confirmed' },
  { category: 'Webhooks', tutorLms: 'N/A (inbound only via WP REST API)', lastsaas: 'Outbound webhook dispatcher with retry + crypto signing', status: 'lastsaas-only', tutorSource: 'N/A', lastsaasSource: 'lastsaas/backend/internal/webhooks/dispatcher.go', confidence: 'confirmed' },
  { category: 'Email', tutorLms: '54 email templates (to_*.php) + WP wp_mail()', lastsaas: 'Resend API integration (email/resend.go)', status: 'different-implementation', tutorSource: 'tutor-pro/templates/email/', lastsaasSource: 'lastsaas/backend/internal/email/resend.go', confidence: 'confirmed' },
  { category: 'Frontend', tutorLms: 'PHP templates + jQuery + some React (v2-library)', lastsaas: 'React 19 + Vite + TanStack Query + Tailwind v4', status: 'different-implementation', tutorSource: 'tutor/templates/, tutor/v2-library/', lastsaasSource: 'lastsaas/frontend/src/', confidence: 'confirmed' },
  { category: 'Database', tutorLms: 'MySQL (WordPress wp_posts + custom tables)', lastsaas: 'MongoDB (38 collections with JSON schema validation)', status: 'different-implementation', tutorSource: 'tutor/migrations/', lastsaasSource: 'lastsaas/backend/internal/db/schema.go, mongodb.go', confidence: 'confirmed' },
  { category: 'Certificate Builder', tutorLms: 'Visual canvas builder (tutor-pro/addons/tutor-certificate/)', lastsaas: 'N/A — new certificate module needed', status: 'missing-in-lastsaas', tutorSource: 'tutor-pro/addons/tutor-certificate/', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'AI Studio', tutorLms: 'OpenAI API passthrough (tutor-pro/tutorai/)', lastsaas: 'N/A — new AI module needed', status: 'missing-in-lastsaas', tutorSource: 'tutor-pro/tutorai/, tutor-pro/openai/', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'Content Drip', tutorLms: '4 drip types (tutor-pro/addons/content-drip/)', lastsaas: 'N/A — new drip module needed', status: 'missing-in-lastsaas', tutorSource: 'tutor-pro/addons/content-drip/', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'Multi-instructor', tutorLms: 'N:N with revenue share (tutor-pro/addons/tutor-multi-instructors/)', lastsaas: 'N/A — new instructor module needed', status: 'missing-in-lastsaas', tutorSource: 'tutor-pro/addons/tutor-multi-instructors/', lastsaasSource: 'N/A', confidence: 'confirmed' },
  { category: 'Gamification', tutorLms: 'Points, badges, leaderboards (via GamiPress)', lastsaas: 'N/A — new gamification module needed', status: 'missing-in-lastsaas', tutorSource: 'tutor/assets/icons/ (gamification icons)', lastsaasSource: 'N/A', confidence: 'inferred' },
  { category: 'Notifications', tutorLms: 'On-site bell + browser toast (tutor-pro/addons/tutor-notifications/)', lastsaas: 'In-app messages + announcements (messages collection)', status: 'partially-implemented', tutorSource: 'tutor-pro/addons/tutor-notifications/', lastsaasSource: 'lastsaas/backend/internal/models/message.go', confidence: 'confirmed' },
  { category: 'Config Store', tutorLms: 'WordPress get_option() / update_option()', lastsaas: 'MongoDB-backed configstore with in-memory cache + dynamic reload', status: 'different-implementation', tutorSource: 'tutor/classes/Tutor.php (default_options)', lastsaasSource: 'lastsaas/backend/internal/configstore/', confidence: 'confirmed' },
  { category: 'Health Monitoring', tutorLms: 'N/A', lastsaas: 'Active node tracking + system metrics + third-party health checks + leader election', status: 'lastsaas-only', tutorSource: 'N/A', lastsaasSource: 'lastsaas/backend/internal/health/', confidence: 'confirmed' },
  { category: 'Telemetry', tutorLms: 'N/A', lastsaas: 'Client-side telemetry + usage events + daily metrics', status: 'lastsaas-only', tutorSource: 'N/A', lastsaasSource: 'lastsaas/backend/internal/telemetry/', confidence: 'confirmed' },
]

export async function GET() {
  return NextResponse.json({ total: comparisons.length, comparisons })
}
